/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMMS.FrontEnd;

import CMMS.Models.note;
import CMMS.ServiceLayer.NoteServiceLayer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ransa
 */
public class view_Note_Panel extends javax.swing.JPanel {

    /**
     * Creates new form view_Note_Panel
     */
    int branchID = 0;
    public view_Note_Panel( String brID ) {
        initComponents();
        branchID = Integer.parseInt(brID);
        LoadNotes();
    }

    //Fetching notes
    public void LoadNotes ()
    {
        ArrayList<note> allnte = NoteServiceLayer.GetUnreadNote(branchID);
        
        DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : allnte ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NoteTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMntId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chkReadNote = new javax.swing.JCheckBox();
        chkUpdatedNotes = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(1280, 968));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Notes");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);

        NoteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maintenance ID", "Supplier ID", "Note", "Cost"
            }
        ));
        NoteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoteTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(NoteTable);

        jLabel2.setText("Maintenance ID: ");

        jButton1.setText("Mark as read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chkReadNote.setText("Show read notes");
        chkReadNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReadNoteActionPerformed(evt);
            }
        });

        chkUpdatedNotes.setText("Show updated notes");
        chkUpdatedNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUpdatedNotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtMntId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkReadNote)
                            .addComponent(chkUpdatedNotes))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMntId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(chkReadNote))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(chkUpdatedNotes))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //Search button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String serKey = txtMntId.getText();
        if ( serKey == null ) {
            JOptionPane.showMessageDialog(this, "Please provide valid Note ID!", "Error!", 2);
        }
        ArrayList<note> serNote = NoteServiceLayer.SearchNote(serKey, branchID);
        if ( serNote.size() > 0 )
        {
            DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : serNote ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Note ID!", "Error!", 2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    //Marks as read button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String serKey = txtMntId.getText();
        if ( serKey == null ) {
            JOptionPane.showMessageDialog(this, "Please provide valid Note ID!", "Error!", 2);
        }
        boolean res = NoteServiceLayer.updateViewStatus(serKey);
        if ( res ){
            ArrayList<note> allnte = NoteServiceLayer.GetUnreadNote(branchID);
        
        DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : allnte ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Note ID!", "Error!", 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //View read notes
    private void chkReadNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReadNoteActionPerformed
        if ( chkReadNote.isSelected() == true )
        {
            ArrayList<note> readnte = NoteServiceLayer.GetReadNote(branchID);
        
        DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : readnte ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
        } else {
            ArrayList<note> allnte = NoteServiceLayer.GetUnreadNote(branchID);
        
        DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : allnte ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
        }
    }//GEN-LAST:event_chkReadNoteActionPerformed

    //View updated notes
    private void chkUpdatedNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUpdatedNotesActionPerformed
        if ( chkUpdatedNotes.isSelected() == true )
        {
            ArrayList<note> updnte = NoteServiceLayer.GetUpdateNote(branchID);
        
        DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : updnte ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
        } else {
            ArrayList<note> allnte = NoteServiceLayer.GetUnreadNote(branchID);
        
        DefaultTableModel dtm = (DefaultTableModel) NoteTable.getModel();
        dtm.setRowCount(0);
        
        for ( note nte : allnte ){
            Object[] rowData = {
                nte.getMntID(),
                nte.getSupID(),
                nte.getDetails(),
                nte.getCost()
            };
            
            dtm.addRow(rowData);
        }
        }
    }//GEN-LAST:event_chkUpdatedNotesActionPerformed

    private void NoteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoteTableMouseClicked
        String mntid = NoteTable.getModel().getValueAt(NoteTable.getSelectedRow(), 0).toString();
       txtMntId.setText(mntid);
    }//GEN-LAST:event_NoteTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable NoteTable;
    private javax.swing.JCheckBox chkReadNote;
    private javax.swing.JCheckBox chkUpdatedNotes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMntId;
    // End of variables declaration//GEN-END:variables
}
